### ISSUE TITLE
NixOS + Stow

### ISSUE THREAD

**Issue by dmadisetti** [erplsf/.dotfiles#1]
It looks like you're just getting started with Nix? Here is my shameless self plug for my dots: https://github.com/dmadisetti/.dots

I think you could get rid of `setup.sh` for `stow` and reconfigure the `dot` directory into stow form.

I don't fully like total configuration in Nix, since it is not cross platform compatible, so symlinks are my compromise.

**Comment by erplsf** [comment]
hi. that script is long gone. what i'm currently is using is `stow` on any folder i need. but the plan is to later migrate this repo to support full nix config like here https://github.com/hlissner/dotfiles - so I already have great configs to look up to.
but still thanks for passing by!

**Comment by dmadisetti** [comment]
Cool! Good luck!
